[versions]
agp = "8.3.2"
exif_interface = "1.3.3"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
metadataExtractor = "2.19.0"
roomRuntime = "2.6.1"
roomRuntimeVersion = "2.5.0"
sqlite = "2.4.0"

[libraries]
exif_interface = { module = "androidx.exifinterface:exif interface", version.ref = "exif_interface" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exif_interface" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
metadata-extractor = { module = "com.drewnoakes:metadata-extractor", version.ref = "metadataExtractor" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-runtime-v250 = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

